# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 647)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d4d4d4;\n"
"    border-radius: 4px;\n"
"    background: white;\n"
"    margin: 5px;\n"
"}\n"
"QTabBar::tab {\n"
"    background: #e0e0e0;\n"
"    border: 1px solid #d4d4d4;\n"
"    padding: 8px 12px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 120px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    border-bottom-color: white;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 14px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 4px;\n"
"    min-width: 120px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}\n"
"QLabel {\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit {\n"
"    padding: 5px;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 4px;\n"
"    min-width: 60px;\n"
"}\n"
"QTableWidget {\n"
"    alternate-background-color: #f9f9f9;\n"
"    selection-background-color: #e0f7fa;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"QFrame {\n"
"    margin: 2px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 1px solid #d4d4d4;\n"
"    border-radius: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dashboard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.dashboard)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_2.addWidget(self.stopButton)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.statusLabel = QtWidgets.QLabel(parent=self.frame_3)
        self.statusLabel.setStyleSheet("font-weight: bold;\n"
"font-size: 16px;")
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.updateLabel = QtWidgets.QLabel(parent=self.frame_3)
        self.updateLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.updateLabel.setObjectName("updateLabel")
        self.verticalLayout_3.addWidget(self.updateLabel)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setStyleSheet("font-weight: bold;\n"
"font-size: 16px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_9 = QtWidgets.QFrame(parent=self.dashboard)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tempSetLabel = QtWidgets.QLabel(parent=self.frame_9)
        self.tempSetLabel.setObjectName("tempSetLabel")
        self.horizontalLayout_5.addWidget(self.tempSetLabel)
        self.tempMinInput = QtWidgets.QLineEdit(parent=self.frame_9)
        self.tempMinInput.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tempMinInput.setObjectName("tempMinInput")
        self.horizontalLayout_5.addWidget(self.tempMinInput)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.tempMaxInput = QtWidgets.QLineEdit(parent=self.frame_9)
        self.tempMaxInput.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tempMaxInput.setObjectName("tempMaxInput")
        self.horizontalLayout_5.addWidget(self.tempMaxInput)
        self.humiditySetLabel = QtWidgets.QLabel(parent=self.frame_9)
        self.humiditySetLabel.setObjectName("humiditySetLabel")
        self.horizontalLayout_5.addWidget(self.humiditySetLabel)
        self.humidityMinInput = QtWidgets.QLineEdit(parent=self.frame_9)
        self.humidityMinInput.setMaximumSize(QtCore.QSize(80, 16777215))
        self.humidityMinInput.setObjectName("humidityMinInput")
        self.horizontalLayout_5.addWidget(self.humidityMinInput)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.humidityMaxInput = QtWidgets.QLineEdit(parent=self.frame_9)
        self.humidityMaxInput.setMaximumSize(QtCore.QSize(80, 16777215))
        self.humidityMaxInput.setObjectName("humidityMaxInput")
        self.horizontalLayout_5.addWidget(self.humidityMaxInput)
        self.setPointButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.setPointButton.setObjectName("setPointButton")
        self.horizontalLayout_5.addWidget(self.setPointButton)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_5 = QtWidgets.QFrame(parent=self.dashboard)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.locationLabel = QtWidgets.QLabel(parent=self.frame_5)
        self.locationLabel.setStyleSheet("font-weight: bold;")
        self.locationLabel.setObjectName("locationLabel")
        self.horizontalLayout_3.addWidget(self.locationLabel)
        self.sensorIdLabel = QtWidgets.QLabel(parent=self.frame_5)
        self.sensorIdLabel.setStyleSheet("font-weight: bold;")
        self.sensorIdLabel.setObjectName("sensorIdLabel")
        self.horizontalLayout_3.addWidget(self.sensorIdLabel)
        self.processStageLabel = QtWidgets.QLabel(parent=self.frame_5)
        self.processStageLabel.setStyleSheet("font-weight: bold;")
        self.processStageLabel.setObjectName("processStageLabel")
        self.horizontalLayout_3.addWidget(self.processStageLabel)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.dashboard)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_4.setStyleSheet("font-weight: bold;\n"
"font-size: 16px;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.temperatureChartView = QtWidgets.QGraphicsView(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureChartView.sizePolicy().hasHeightForWidth())
        self.temperatureChartView.setSizePolicy(sizePolicy)
        self.temperatureChartView.setObjectName("temperatureChartView")
        self.verticalLayout_6.addWidget(self.temperatureChartView)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_5.setStyleSheet("font-weight: bold;\n"
"font-size: 16px;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.humidityChartView = QtWidgets.QGraphicsView(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityChartView.sizePolicy().hasHeightForWidth())
        self.humidityChartView.setSizePolicy(sizePolicy)
        self.humidityChartView.setObjectName("humidityChartView")
        self.verticalLayout_5.addWidget(self.humidityChartView)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_6)
        self.tabWidget.addTab(self.dashboard, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.judulTAbel = QtWidgets.QLabel(parent=self.frame_10)
        self.judulTAbel.setStyleSheet("font-weight: bold;\n"
"font-size: 18px;")
        self.judulTAbel.setObjectName("judulTAbel")
        self.horizontalLayout_6.addWidget(self.judulTAbel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.refreshButton = QtWidgets.QPushButton(parent=self.frame_10)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_6.addWidget(self.refreshButton)
        self.exportButton = QtWidgets.QPushButton(parent=self.frame_10)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_6.addWidget(self.exportButton)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monitoring System - Kelompok 10"))
        self.startButton.setText(_translate("MainWindow", "Start Monitoring"))
        self.stopButton.setText(_translate("MainWindow", "Stop Monitoring"))
        self.statusLabel.setText(_translate("MainWindow", "STATUS: OFFLINE"))
        self.updateLabel.setText(_translate("MainWindow", "Last Update: --/--/---- --:--:--"))
        self.label.setText(_translate("MainWindow", "KELOMPOK 10"))
        self.label_2.setText(_translate("MainWindow", "Rizal Khoirul Atok\n"
"Muhammad Emir Hakim Zauhari\n"
"Daffa Naufal Wahyuaji"))
        self.label_3.setText(_translate("MainWindow", "2042231013\n"
"2042231069\n"
"2042231081"))
        self.tempSetLabel.setText(_translate("MainWindow", "Set Point Suhu (°C):"))
        self.tempMinInput.setText(_translate("MainWindow", "25.0"))
        self.label_6.setText(_translate("MainWindow", "to"))
        self.tempMaxInput.setText(_translate("MainWindow", "30.0"))
        self.humiditySetLabel.setText(_translate("MainWindow", "Set Point Kelembaban (%):"))
        self.humidityMinInput.setText(_translate("MainWindow", "70.0"))
        self.label_7.setText(_translate("MainWindow", "to"))
        self.humidityMaxInput.setText(_translate("MainWindow", "80.0"))
        self.setPointButton.setText(_translate("MainWindow", "Update Set Point"))
        self.locationLabel.setText(_translate("MainWindow", "Location: -"))
        self.sensorIdLabel.setText(_translate("MainWindow", "Sensor ID: -"))
        self.processStageLabel.setText(_translate("MainWindow", "Process Stage: -"))
        self.label_4.setText(_translate("MainWindow", "Temperature Monitoring"))
        self.label_5.setText(_translate("MainWindow", "Humidity Monitoring"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dashboard), _translate("MainWindow", "Dashboard"))
        self.judulTAbel.setText(_translate("MainWindow", "DATA SENSOR SHT20"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh Data"))
        self.exportButton.setText(_translate("MainWindow", "Export to Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Sensor"))
